/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Cad_Grupo.java
 *
 * Created on 12/09/2010, 11:53:53
 */

package autopecas.visao;

import autopecas.logica.data;

/**
 *
 * @author caitanojunior
 */
public class Cad_Grupo extends javax.swing.JFrame {

    data mostra_data;//variavel que vai chamar os metodos da data e hora
    /** Creates new form Cad_Grupo */
    public Cad_Grupo() {
        initComponents();
        mostra_data = new data();//objeto inicializado
        mostra_data.le_data();
        jLabel_data.setText(mostra_data.dia_semana + ", " +
                            mostra_data.dia + " de " +
                            mostra_data.mes + " de " +
                            mostra_data.ano);

        timer1.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timer1 = new org.netbeans.examples.lib.timerbean.Timer();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_codigo = new javax.swing.JTextField();
        tf_nome = new javax.swing.JTextField();
        botao_novo = new javax.swing.JButton();
        botao_salvar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        botao_excluir = new javax.swing.JButton();
        botao_sair = new javax.swing.JButton();
        jLabel_data = new javax.swing.JLabel();
        jLabel_hora = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();

        timer1.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                timer1OnTime(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Grupos");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14));
        jLabel1.setText("Código:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14));
        jLabel2.setText("Nome:");

        tf_codigo.setFont(new java.awt.Font("Arial", 0, 14));

        tf_nome.setFont(new java.awt.Font("Arial", 0, 14));

        botao_novo.setIcon(new javax.swing.ImageIcon("C:\\icones\\novo_reg.gif")); // NOI18N
        botao_novo.setText("Novo Registro");
        botao_novo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botao_novo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        botao_novo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        botao_salvar.setIcon(new javax.swing.ImageIcon("C:\\icones\\GRAVAR2.jpg")); // NOI18N
        botao_salvar.setText("Salvar Registro");
        botao_salvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botao_salvar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        botao_salvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\icones\\alterar_dados.jpg")); // NOI18N
        jButton3.setText("Alterar Registro");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        botao_excluir.setIcon(new javax.swing.ImageIcon("C:\\icones\\EXCLUIR.jpg")); // NOI18N
        botao_excluir.setText("Excluir Registro");
        botao_excluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botao_excluir.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        botao_excluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        botao_sair.setIcon(new javax.swing.ImageIcon("C:\\icones\\sair2.gif")); // NOI18N
        botao_sair.setText("Sair");
        botao_sair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botao_sair.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        botao_sair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botao_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_sairActionPerformed(evt);
            }
        });

        jLabel_data.setText("data");

        jLabel_hora.setText("hora");

        jMenu2.setText("Sair");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel_data)
                    .addComponent(jLabel_hora))
                .addContainerGap(429, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addComponent(botao_novo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botao_salvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botao_excluir)
                .addGap(6, 6, 6)
                .addComponent(botao_sair)
                .addGap(113, 113, 113))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botao_excluir, botao_novo, botao_sair, botao_salvar, jButton3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 306, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botao_sair)
                    .addComponent(botao_excluir)
                    .addComponent(botao_novo)
                    .addComponent(botao_salvar)
                    .addComponent(jButton3))
                .addGap(65, 65, 65)
                .addComponent(jLabel_data)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_hora)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botao_excluir, botao_novo, botao_sair, botao_salvar, jButton3});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void timer1OnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timer1OnTime
         // evento do timer1 que mostra os segundos
        mostra_data.le_hora();
        jLabel_hora.setText(mostra_data.hora);
    }//GEN-LAST:event_timer1OnTime

    private void botao_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_sairActionPerformed
        // evento botao sair
        dispose();
    }//GEN-LAST:event_botao_sairActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cad_Grupo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_excluir;
    private javax.swing.JButton botao_novo;
    private javax.swing.JButton botao_sair;
    private javax.swing.JButton botao_salvar;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_data;
    private javax.swing.JLabel jLabel_hora;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField tf_codigo;
    private javax.swing.JTextField tf_nome;
    private org.netbeans.examples.lib.timerbean.Timer timer1;
    // End of variables declaration//GEN-END:variables

}
