/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Tela_Principal.java
 *
 * Created on 09/08/2010, 16:23:05
 */

package autopecas.visao;

import autopecas.logica.data;
import javax.swing.JOptionPane;

/**
 *
 * @author Junior
 */
public class Tela_Principal extends javax.swing.JFrame {
    data mostra_data;//variavel que vai chamar os metodos da data e hora
    /** Creates new form Tela_Principal */
    public Tela_Principal() {
        initComponents();
        mostra_data = new data();//objeto inicializado
        mostra_data.le_data();
        jLabel_data.setText(mostra_data.dia_semana + ", " +
                            mostra_data.dia + " de " +
                            mostra_data.mes + " de " +
                            mostra_data.ano);

        timer1.start();
    } 
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timer1 = new org.netbeans.examples.lib.timerbean.Timer();
        jPanel1 = new javax.swing.JPanel();
        jButton_produtos = new javax.swing.JButton();
        jButton_sair = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel_hora = new javax.swing.JLabel();
        jLabel_data = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_cadastros = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu_sair = new javax.swing.JMenu();

        timer1.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                timer1OnTime(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Auto Peças - Controle de Estoque");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton_produtos.setFont(new java.awt.Font("Arial", 0, 12));
        jButton_produtos.setText("Entrada de Material");
        jButton_produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_produtosActionPerformed(evt);
            }
        });

        jButton_sair.setFont(new java.awt.Font("Arial", 0, 12));
        jButton_sair.setText("Sair");
        jButton_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_sairActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial", 0, 12));
        jButton1.setText("Vendas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_produtos, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_sair, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton_produtos});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jButton_produtos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_sair)
                .addContainerGap(383, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton_produtos, jButton_sair});

        jLabel_hora.setText("hora");

        jLabel_data.setText("data");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 48));
        jLabel1.setText("EstoqueTools");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel2.setText("Controle de Estoque");

        jMenuBar1.setBackground(new java.awt.Color(0, 204, 51));

        jMenu_cadastros.setBackground(new java.awt.Color(0, 204, 0));
        jMenu_cadastros.setText("Cadastros");

        jMenuItem3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem3.setText("Cadastro de Produtos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu_cadastros.add(jMenuItem3);

        jMenuItem1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem1.setText("Cadastro de Clientes");
        jMenu_cadastros.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem2.setText("Cadastro de Fornecedores");
        jMenu_cadastros.add(jMenuItem2);

        jMenuItem4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem4.setText("Cadastro de Funcionários");
        jMenu_cadastros.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem5.setText("Sair");
        jMenu_cadastros.add(jMenuItem5);

        jMenuBar1.add(jMenu_cadastros);

        jMenu_sair.setBackground(new java.awt.Color(0, 204, 0));
        jMenu_sair.setText("Sair");
        jMenu_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_sairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu_sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_data)
                                .addComponent(jLabel_hora))
                            .addContainerGap(595, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel1)
                            .addGap(182, 182, 182)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(238, 238, 238))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(250, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(199, 199, 199)
                .addComponent(jLabel_data)
                .addGap(4, 4, 4)
                .addComponent(jLabel_hora)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-808)/2, (screenSize.height-634)/2, 808, 634);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu_sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_sairMouseClicked
        // Evento do menu_sair
        try {
            String nome = "Tem certeza que deseja sair do sistema?";
            int opcao_escolhida = JOptionPane.showConfirmDialog(null, nome, "Sair", JOptionPane.YES_NO_OPTION);
            if(opcao_escolhida == JOptionPane.YES_OPTION){
                System.exit(0);
            }
        }catch(Exception erro){
            JOptionPane.showMessageDialog(null, "Erro ao fechar o sistema! "+erro);
        }
    }//GEN-LAST:event_jMenu_sairMouseClicked

    private void timer1OnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timer1OnTime
        // evento do timer1 que mostra os segundos
        mostra_data.le_hora();
        jLabel_hora.setText(mostra_data.hora);
    }//GEN-LAST:event_timer1OnTime

    private void jButton_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sairActionPerformed
        // Evento do botão sair
        try {
            String pergunta = "Tem certeza que deseja sair do sistema?";
            int opcao_escolhida = JOptionPane.showConfirmDialog(null, pergunta, "Sair", JOptionPane.YES_NO_OPTION);
            if(opcao_escolhida == JOptionPane.YES_OPTION){
                System.exit(0);
            }
        }catch(Exception erro){
            JOptionPane.showMessageDialog(null, "Erro ao fechar o sistema! "+erro);
        }
}//GEN-LAST:event_jButton_sairActionPerformed

    private void jButton_produtosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_produtosActionPerformed
        // evento do botão entrada de material
        new Entrada_material().show();
    }//GEN-LAST:event_jButton_produtosActionPerformed

    private void jMenuItem_cad_fornecedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem_cad_fornecedorMousePressed
        // evento do botao jMenuItem_cad_fornecedor
        new Cad_fornecedor().show();
    }//GEN-LAST:event_jMenuItem_cad_fornecedorMousePressed

    private void jMenuItem_sairMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem_sairMousePressed
         // Evento do jmenu_sair
        try {
            String nome = "Tem certeza que deseja sair do sistema?";
            int opcao_escolhida = JOptionPane.showConfirmDialog(null, nome, "Sair", JOptionPane.YES_NO_OPTION);
            if(opcao_escolhida == JOptionPane.YES_OPTION){
                System.exit(0);
            }
        }catch(Exception erro){
            JOptionPane.showMessageDialog(null, "Erro ao fechar o sistema! "+erro);
        }
    }//GEN-LAST:event_jMenuItem_sairMousePressed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        new Cad_produto().show();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_produtos;
    private javax.swing.JButton jButton_sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_data;
    private javax.swing.JLabel jLabel_hora;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenu jMenu_cadastros;
    private javax.swing.JMenu jMenu_sair;
    private javax.swing.JPanel jPanel1;
    private org.netbeans.examples.lib.timerbean.Timer timer1;
    // End of variables declaration//GEN-END:variables

}
