/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Tela_Principal.java
 *
 * Created on 09/08/2010, 16:23:05
 */

package autopecas.visao;

import autopecas.logica.data;
import javax.swing.JOptionPane;

/**
 *
 * @author Junior
 */
public class Tela_Principal extends javax.swing.JFrame {
    data mostra_data;//variavel que vai chamar os metodos da data e hora
    /** Creates new form Tela_Principal */
    public Tela_Principal() {
        initComponents();
        mostra_data = new data();//objeto inicializado
        mostra_data.le_data();
        jLabel_data.setText(mostra_data.dia_semana + ", " +
                            mostra_data.dia + " de " +
                            mostra_data.mes + " de " +
                            mostra_data.ano);

        timer1.start();
    } 
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timer1 = new org.netbeans.examples.lib.timerbean.Timer();
        jPanel1 = new javax.swing.JPanel();
        botao_entrada_mat = new javax.swing.JButton();
        botao_sair = new javax.swing.JButton();
        botao_vendas = new javax.swing.JButton();
        jLabel_hora = new javax.swing.JLabel();
        jLabel_data = new javax.swing.JLabel();
        jLabel_nome_sistema = new javax.swing.JLabel();
        jLabel_cont_estoque = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_cadastros = new javax.swing.JMenu();
        jMenuItem_cad_clientes = new javax.swing.JMenuItem();
        jMenuItem_Cad_Fabricantes = new javax.swing.JMenuItem();
        jMenuItem_cad_Fornecedores = new javax.swing.JMenuItem();
        jMenuItem_cad_Funcionarios = new javax.swing.JMenuItem();
        jMenuItem_cad_Grupos = new javax.swing.JMenuItem();
        jMenuItem_Cad_Produto = new javax.swing.JMenuItem();
        jMenuItem_sair = new javax.swing.JMenuItem();
        jMenu_sair = new javax.swing.JMenu();

        timer1.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                timer1OnTime(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Auto Peças - Controle de Estoque");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        botao_entrada_mat.setFont(new java.awt.Font("Arial", 0, 12));
        botao_entrada_mat.setText("Entrada de Material");
        botao_entrada_mat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_entrada_matActionPerformed(evt);
            }
        });

        botao_sair.setFont(new java.awt.Font("Arial", 0, 12));
        botao_sair.setText("Sair");
        botao_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_sairActionPerformed(evt);
            }
        });

        botao_vendas.setFont(new java.awt.Font("Arial", 0, 12));
        botao_vendas.setText("Vendas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botao_vendas, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_entrada_mat, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_sair, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botao_entrada_mat, botao_vendas});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(botao_entrada_mat, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botao_vendas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botao_sair)
                .addContainerGap(383, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botao_entrada_mat, botao_sair, botao_vendas});

        jLabel_hora.setText("hora");

        jLabel_data.setText("data");

        jLabel_nome_sistema.setFont(new java.awt.Font("Times New Roman", 0, 48));
        jLabel_nome_sistema.setText("EstoqueTools");

        jLabel_cont_estoque.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel_cont_estoque.setText("Controle de Estoque");

        jMenuBar1.setBackground(new java.awt.Color(0, 204, 51));

        jMenu_cadastros.setBackground(new java.awt.Color(0, 204, 0));
        jMenu_cadastros.setText("Cadastros");

        jMenuItem_cad_clientes.setFont(new java.awt.Font("Arial", 0, 14));
        jMenuItem_cad_clientes.setIcon(new javax.swing.ImageIcon("C:\\icones\\cliente.gif")); // NOI18N
        jMenuItem_cad_clientes.setText("Cadastro de Clientes");
        jMenu_cadastros.add(jMenuItem_cad_clientes);

        jMenuItem_Cad_Fabricantes.setFont(new java.awt.Font("Arial", 0, 14));
        jMenuItem_Cad_Fabricantes.setIcon(new javax.swing.ImageIcon("C:\\icones\\tool.gif")); // NOI18N
        jMenuItem_Cad_Fabricantes.setText("Cadastro de Fabricantes");
        jMenuItem_Cad_Fabricantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem_Cad_FabricantesMousePressed(evt);
            }
        });
        jMenu_cadastros.add(jMenuItem_Cad_Fabricantes);

        jMenuItem_cad_Fornecedores.setFont(new java.awt.Font("Arial", 0, 14));
        jMenuItem_cad_Fornecedores.setIcon(new javax.swing.ImageIcon("C:\\icones\\fornecedor2.png")); // NOI18N
        jMenuItem_cad_Fornecedores.setText("Cadastro de Fornecedores");
        jMenuItem_cad_Fornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem_cad_FornecedoresMousePressed(evt);
            }
        });
        jMenu_cadastros.add(jMenuItem_cad_Fornecedores);

        jMenuItem_cad_Funcionarios.setFont(new java.awt.Font("Arial", 0, 14));
        jMenuItem_cad_Funcionarios.setIcon(new javax.swing.ImageIcon("C:\\icones\\icone_cadastro_cliente.jpg")); // NOI18N
        jMenuItem_cad_Funcionarios.setText("Cadastro de Funcionários");
        jMenu_cadastros.add(jMenuItem_cad_Funcionarios);

        jMenuItem_cad_Grupos.setFont(new java.awt.Font("Arial", 0, 14));
        jMenuItem_cad_Grupos.setIcon(new javax.swing.ImageIcon("C:\\icones\\grupo.png")); // NOI18N
        jMenuItem_cad_Grupos.setText("Cadastro de Grupos");
        jMenuItem_cad_Grupos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem_cad_GruposMousePressed(evt);
            }
        });
        jMenu_cadastros.add(jMenuItem_cad_Grupos);

        jMenuItem_Cad_Produto.setFont(new java.awt.Font("Arial", 0, 14));
        jMenuItem_Cad_Produto.setIcon(new javax.swing.ImageIcon("C:\\icones\\produto.gif")); // NOI18N
        jMenuItem_Cad_Produto.setText("Cadastro de Produtos");
        jMenuItem_Cad_Produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Cad_ProdutoActionPerformed(evt);
            }
        });
        jMenu_cadastros.add(jMenuItem_Cad_Produto);

        jMenuItem_sair.setFont(new java.awt.Font("Arial", 0, 14));
        jMenuItem_sair.setIcon(new javax.swing.ImageIcon("C:\\icones\\sair2.gif")); // NOI18N
        jMenuItem_sair.setText("Sair");
        jMenu_cadastros.add(jMenuItem_sair);

        jMenuBar1.add(jMenu_cadastros);

        jMenu_sair.setBackground(new java.awt.Color(0, 204, 0));
        jMenu_sair.setText("Sair");
        jMenu_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_sairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu_sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_data)
                                .addComponent(jLabel_hora))
                            .addContainerGap(595, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel_nome_sistema)
                            .addGap(182, 182, 182)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_cont_estoque)
                        .addGap(238, 238, 238))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(250, Short.MAX_VALUE)
                .addComponent(jLabel_nome_sistema, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_cont_estoque)
                .addGap(199, 199, 199)
                .addComponent(jLabel_data)
                .addGap(4, 4, 4)
                .addComponent(jLabel_hora)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-808)/2, (screenSize.height-634)/2, 808, 634);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu_sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_sairMouseClicked
        // Evento do menu_sair
        try {
            String nome = "Tem certeza que deseja sair do sistema?";
            int opcao_escolhida = JOptionPane.showConfirmDialog(null, nome, "Sair", JOptionPane.YES_NO_OPTION);
            if(opcao_escolhida == JOptionPane.YES_OPTION){
                System.exit(0);
            }
        }catch(Exception erro){
            JOptionPane.showMessageDialog(null, "Erro ao fechar o sistema! "+erro);
        }
    }//GEN-LAST:event_jMenu_sairMouseClicked

    private void timer1OnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timer1OnTime
        // evento do timer1 que mostra os segundos
        mostra_data.le_hora();
        jLabel_hora.setText(mostra_data.hora);
    }//GEN-LAST:event_timer1OnTime

    private void botao_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_sairActionPerformed
        // Evento do botão sair
        try {
            String pergunta = "Tem certeza que deseja sair do sistema?";
            int opcao_escolhida = JOptionPane.showConfirmDialog(null, pergunta, "Sair", JOptionPane.YES_NO_OPTION);
            if(opcao_escolhida == JOptionPane.YES_OPTION){
                System.exit(0);
            }
        }catch(Exception erro){
            JOptionPane.showMessageDialog(null, "Erro ao fechar o sistema! "+erro);
        }
}//GEN-LAST:event_botao_sairActionPerformed

    private void botao_entrada_matActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_entrada_matActionPerformed
        // evento do botão entrada de material
        new Entrada_material().show();
    }//GEN-LAST:event_botao_entrada_matActionPerformed

    private void jMenuItem_cad_fornecedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem_cad_fornecedorMousePressed
        // evento do botao jMenuItem_cad_fornecedor
        new Cad_fornecedor().show();
    }//GEN-LAST:event_jMenuItem_cad_fornecedorMousePressed

    private void jMenuItem_Cad_ProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Cad_ProdutoActionPerformed
        new Cad_produto().show();
        // chamada da tela cad_produto
    }//GEN-LAST:event_jMenuItem_Cad_ProdutoActionPerformed

    private void jMenuItem_sairMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem5MousePressed
    // Evento do botão sair
        try {
            String pergunta = "Tem certeza que deseja sair do sistema?";
            int opcao_escolhida = JOptionPane.showConfirmDialog(null, pergunta, "Sair", JOptionPane.YES_NO_OPTION);
            if(opcao_escolhida == JOptionPane.YES_OPTION){
                System.exit(0);
            }
        }catch(Exception erro){
            JOptionPane.showMessageDialog(null, "Erro ao fechar o sistema! "+erro);
        }
    }//GEN-LAST:event_jMenuItem5MousePressed

    private void jMenuItem_cad_GruposMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem_cad_GruposMousePressed
        //chamada da tela cad_grupos
        new Cad_Grupo().show();
    }//GEN-LAST:event_jMenuItem_cad_GruposMousePressed

    private void jMenuItem_cad_FornecedoresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem_cad_FornecedoresMousePressed
        //chamada da tela cad_fornecedores
        new Cad_fornecedor().show();
    }//GEN-LAST:event_jMenuItem_cad_FornecedoresMousePressed

    private void jMenuItem_Cad_FabricantesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem_Cad_FabricantesMousePressed
       //chamada da tela fabricante
        new Cad_fabricante().show();
    }//GEN-LAST:event_jMenuItem_Cad_FabricantesMousePressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_entrada_mat;
    private javax.swing.JButton botao_sair;
    private javax.swing.JButton botao_vendas;
    private javax.swing.JLabel jLabel_cont_estoque;
    private javax.swing.JLabel jLabel_data;
    private javax.swing.JLabel jLabel_hora;
    private javax.swing.JLabel jLabel_nome_sistema;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_Cad_Fabricantes;
    private javax.swing.JMenuItem jMenuItem_Cad_Produto;
    private javax.swing.JMenuItem jMenuItem_cad_Fornecedores;
    private javax.swing.JMenuItem jMenuItem_cad_Funcionarios;
    private javax.swing.JMenuItem jMenuItem_cad_Grupos;
    private javax.swing.JMenuItem jMenuItem_cad_clientes;
    private javax.swing.JMenuItem jMenuItem_sair;
    private javax.swing.JMenu jMenu_cadastros;
    private javax.swing.JMenu jMenu_sair;
    private javax.swing.JPanel jPanel1;
    private org.netbeans.examples.lib.timerbean.Timer timer1;
    // End of variables declaration//GEN-END:variables

}
